### ISSUE TITLE
占い機能の実装

### ISSUE THREAD

**Issue by Hosi121** [Hosi121/COGweb#3]
占い機能を実装する．

- 占い用のカスタムフックを用意する．
「今日の運勢はAです．ラッキーアイテムはBです．ラッキーカラーはCです」という形式．乱数を振り，A,B,Cを埋める．

- 占いボタンをクリックすると，占いカスタムフックが呼び出される．
フロントだけで十分．（毎回結果が変わって大丈夫）

- ラッキーアイテムやラッキーカラーはアイコンを出せるとよさそう．
CDNを使うことになりたくないので，仮案ですが [MUIアイコン](https://mui.com/material-ui/material-icons/) なんかで出せるとよさそう．

devブランチで直接pushしてくれて構いません．mainへのmerge PRを見てコードレビューします．

**Comment by araaki12345** [comment]
それはアクセスした時に毎回出るようにしますか？それとも朝だけとか(できるかは検証していないけど)で、時間で区切りますか？
